// Generated by https://quicktype.io
var url = 'data.json';
fetch(url)
    .then(function (response) {
    // Check if the response status is in the range 200-299 (success)
    if (!response.ok) {
        throw new Error("HTTP error! Status: ".concat(response.status));
    }
    // Parse the JSON in the response
    return response.json();
})
    .then(function (data) {
    // let conData = data;
    var newData = Object.values(data);
    var cards = document.querySelectorAll('.cards');
    var elementsArray = Array.from(cards);
    var dailyData = '';
    var daily = newData.map(function (elements) {
        var elementsModifiedArray = elementsArray.map(function (element) {
            // Do something with each element
            element.innerHTML += " <div class=\"card\">\n        <div class=\"inner-card\">\n            <div class=\"status\">\n                <p>".concat(elements.title, "</p>\n                <i class=\"fa fa-ellipsis-h\" aria-hidden=\"true\"></i>\n            </div>\n            <div class=\"time\">\n                <h2>").concat(elements.timeframes.daily.current, "hrs</h2>\n                <p>Last Week - ").concat(elements.timeframes.daily.previous, "hrs</p>\n            </div>\n        </div>\n    </div>");
            console.log(elements.title);
            // console.log(`Element at index :`, element.innerHTML += `<h1>nice</h1>`);
            return element; // You can modify the element or create a new array with modifications
        });
        console.log(elementsModifiedArray);
        console.log(elements.timeframes.daily);
        console.log(elements.timeframes.weekly);
    });
    console.log(newData, typeof (newData));
    // console.log(conData ,typeof(conData));
})["catch"](function (error) {
    // Handle errors during the fetch or JSON parsing
    console.error('Fetch error:', error);
});
// const text: HTMLCollectionBase = document.querySelectorAll('h1');
// const newText: Element[] = Array.from(text);
// newText.forEach(element => {
//   element.innerHTML = '<h1>' + element.innerHTML + '</h1>';
// });
// console.log(text);
// const elements = document.querySelectorAll('.inner-card');
// const elementsArray = Array.from(elements);
// Using .map
// const elementsModifiedArray = elementsArray.map((element) => {
//   // Do something with each element
//   // console.log(`Element at index :`, element.innerHTML += `<h1>nice</h1>`);
//   return element; // You can modify the element or create a new array with modifications
// });
